[project]
name = "mammaprint"
version = "0.1.0"
authors = [
    { name = "Michal Kišš", email = "550439@mail.muni.cz" },
    { name = "Matěj Pekár", email = "matejpekar@mail.muni.cz" },
]
requires-python = ">=3.12, <3.13"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "aiohttp>=3.13.1",
    "hydra-core>=1.3.2",
    "lightning>=2.5.5",
    "omegaconf>=2.3.0",
    "rationai-mlkit>=0.4.0",
    "rationai-masks>=1.1.1",
    "rationai-tiling>=1.1.1",
    "ratiopath>=1.3.1",
    "rationai-sdk"
]

[dependency-groups]
dev = [
    "ruff>=0.14.1",
    "mypy>=1.19.1",
]

[tool.uv.sources]
rationai-masks = { git = "https://gitlab.ics.muni.cz/rationai/digital-pathology/libraries/masks.git" }
rationai-mlkit = { git = "https://gitlab.ics.muni.cz/rationai/digital-pathology/libraries/mlkit.git" }
rationai-tiling = { git = "https://gitlab.ics.muni.cz/rationai/digital-pathology/libraries/tiling.git" }
rationai-sdk = { git = "https://github.com/RationAI/rationai-sdk-python.git" } 
ratiopath = { git = "https://github.com/RationAI/ratiopath.git" }
