defaults:
  - _self_
  - hydra: default
  - mlflow: kubas_cluster
  - metadata: base
  - task: default
  - trainer: default

ml: ???
datamodule: ???
user: ???
seed: ${random_seed:}
use_determinism: False
