attention_visualizer:
  _target_: mammaprint.trainer.callbacks.AttentionVisualizer
  save_dir: ???
  image_builder:
    _target_: mammaprint.trainer.callbacks.image_builders.InMemoryHeatmapAssembler
    _partial_: true
    vis_mode:
      _target_: mammaprint.trainer.callbacks.vis_mode.IdentityMode
    interpolation: nearest
    compress_accumulator_array: true
    