# @package _global_

dataset:
  paths:
    data_mapping: ???
  mlflow_uris:
    tissue_masks: ???

max_concurrent: 3
timeout: 6000
model_name: episeg-1
models_base_url: http://rayservice-model-fix-serve-svc.rationai-jobs-ns.svc.cluster.local:8000

metadata:
  run_name: Mammaprint Epithelium Masks
  description: Generating epithelium masks for mammaprint slides
