# @package _global_

level: 3
max_concurrent: 100
mlflow_artifact_path: tissue_masks

metadata:
  run_name: Mammaprint Tissue Masks
  description: Generating tissue masks for mammaprint slides
  hyperparams:
    level: ${level}
