mammaprint:
  _target_: mammaprint.datamodule.datasources.WSIDataSource
  seed: ${seed}
  data_uris:
    - mlflow-artifacts:/17/6d32e4e0ebe24688b6f5ed582abe0213/artifacts/dataset
  stratified_keys:
    - luminal_id
  splits:
    train: ??
    valid: ??
