mammaprint_test:
  _target_: mammaprint.datamodule.datasources.WSIDataSource
  seed: ${seed}
  data_uris: 
    - mlflow-artifacts:/17/a4b1a67f4da4400b821826e899486a5c/artifacts/train_tissue_classification_tumor_tiles #level1
  splits:
    test: 1.0
