mammaprint_test:
  _target_: mammaprint.datamodule.datasources.WSIDataSource
  seed: ${seed}
  data_uris: 
    - mlflow-artifacts:/17/9fdc56020b9c489fab17e94e33d3e4c1/artifacts/dataset
  splits:
    test: 1.0
