mammaprint_test:
  _target_: mammaprint.datamodule.datasources.WSIDataSource
  seed: ${seed}
  data_uris: 
    - mlflow-artifacts:/17/ed57ee768d8544599e642a0c471d8eb1/artifacts/dataset
  splits:
    test: 1.0
