mammaprint_test:
  _target_: mammaprint.datamodule.datasources.WSIDataSource
  seed: ${seed}
  data_uris: 
    - mlflow-artifacts:/17/b85303ebcfe14a69aea163eebf1c3765/artifacts/activations # mil prostate dataset for test
  splits:
    test: 1.0
