prostate_test:
  _target_: histopipe.datamodule.datasources.WSIDataSource
  seed: ${seed}
  data_uris:
    - mlflow-artifacts:/4/42a6acd9b91942b4838646b6e9a2c158/artifacts/dataset  # Test cases
  splits:
    test: 1.0
