prostate:
  _target_: histopipe.datamodule.datasources.WSIDataSource
  seed: ${seed}
  data_uris:
    #- mlflow-artifacts:/55/4b1c6112d43345fda2ff90fca70abb57/artifacts/dataset # MMCI strict_mode=False
    # - mlflow-artifacts:/17/34960f7abb55464cb8d9266cacb62836/artifacts/dataset # mammaprint small validation dataset
#    - mlflow-artifacts:/17/294101f7fb194114bef0809b9c7c634c/artifacts/dataset # mammaprint full dataset
    - mlflow-artifacts:/17/76c070338fe4407ca1e395c6ddbd3cca/artifacts/dataset # was part 2
  splits:
    test: 1.0
