_target_: ml.callbacks.PredictionCSVCallback
label_mode: ${label_mode}
artifact_path: predictions
filename: predictions.csv
table_filename: predictions.json
classification_outputs_are_logits: true
threshold: 0.5
save_dir: null
