defaults:
  - hydra: default
  - logger: mlflow
  - /data/datasets@data.train: mammaprint/train
  - /data/datasets@data.val: mammaprint/val
  - /data/datasets@data.test: mammaprint/test
  - /data/datasets@data.predict: mammaprint/predict
  - /model/backbone: ???
  - _self_

seed: ${random_seed:}
mode: ???
checkpoint: null

trainer:
  enable_checkpointing: True
  max_epochs: 30
  log_every_n_steps: 5
  limit_train_batches: 0.0125
  limit_val_batches: 0.0125
  callbacks:
    # - _target_: lightning.pytorch.callbacks.ModelCheckpoint
    #   save_top_k: 1
    #   monitor: validation/loss
    #   mode: min
    - _target_: mammaprint.trainer.callbacks.SlidePredictionOptimizer
      save_dir: slide_predictions
      mask_size_min: 1
      mask_size_max: 100
      ground_truth_col: cancer_percentage

data:
  batch_size: 32
  num_workers: 8

metadata:
  experiment_name: Mamma-print
  run_name: 📏 Luminal-type testing - optimizer
  description: Training a model on the luminal-type dataset
  hyperparams: {}

# metadata:
#   experiment_name: Mamma-print
#   run_name: 🏋️‍♂️ Luminal-type training
#   description: Training a model on the luminal-type dataset
#   hyperparams: {}