defaults:
  - hydra: default
  - logger: mlflow
  - _self_

data_path: /mnt/data/MOU/breast/mammaprint
mammaprint_path: /mnt/projects/mammaprint
data_mapping: ${mammaprint_path}/data_mapping.csv

metadata:
  experiment_name: MammaPrint
  run_name: ???
  description: ???
  hyperparams: {}
