_target_: albumentations.Compose
p: 1.0 # default
transforms:
  - _target_: albumentations.Resize
    height: 64
    width: 64
    interpolation: 0 #cv2.INTER_NEAREST
    p: 1.0
  - _target_: albumentations.Normalize
    mean: 0.5
    std: 0.5
    max_pixel_value: 255
    p: 1.0  # default
